CREATE TABLE tbla (year STRING, temp INT, quality INT)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '${TABLE_A_DATA}' OVERWRITE INTO TABLE tbla;

CREATE TABLE tblb (year STRING)
  ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INPATH '${TABLE_B_DATA}' OVERWRITE INTO TABLE tblb;

SELECT a.year, a.temp, a.quality  FROM tbla a JOIN tblb b ON a.year = b.year;
